project:
  type: website
  output-dir: ../docs

website:
  title: "Gary"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: research.qmd
        text: Research

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



